### ISSUE TITLE
MudZoneFactory does not set name. Causes Null Reference crash on worker thread.

### ISSUE THREAD

**Issue by danec020** [MudDesigner/MudEngine#1]
MudZoneFactory.cs takes in the string Name parameter when calling CreateZone method. It does not set the name inside the method which is a requirement inside MudRealm.cs when adding a zone to the list of Zones.

**Comment by scionwest** [comment]
Just to clarify, it is a requirement of `MudZone` and not `MudRealm`. This is now fixed.
