### ISSUE TITLE
MessageBroker.cs Publish method returns early and can hit a null reference exception.

### ISSUE THREAD

**Issue by danec020** [MudDesigner/MudEngine#2]
Inside the foreach loop the handler processes the message than returns which means only one subscriber to that type of message will get called. Also if you remove the return you can get a null reference in the next if statement that follows since attribute can be null. So possibly use "continue" after processing the message to avoid the rest of the method.

**Comment by scionwest** [comment]
The use of the `MessageVerbosityAttribute` is still up in the air for me. I'm not sure that I actually want to use attributes to handle verbosity levels. I'll be ripping that piece out in the future. I recommend you not use that attribute in your code.

In the mean time, I fixed the issue by adding a `continue` to the for-each loop when a message does not have that attribute attached.
