### ISSUE TITLE
MudGame.cs BeginStart method creates a null SynchronizationContext.

### ISSUE THREAD

**Issue by danec020** [MudDesigner/MudEngine#4]
Currently the application is executing in the MainThread which has no SynchronizationContext set. The code then executes the Invoke method inside ThreadContext.cs but issues a null reference exception since the Context passed was null.

Possibly add a check for the passed in ThreadContext parameter that checks it's context for null.

**Comment by scionwest** [comment]
The `BeginStart` method now passes null to `Start()` if there isn't any existing `SynchronizationContext`

**Comment by scionwest** [comment]
Commit ddd286562476efa8616a41561d3617addf46169a fixed this by creating a context if none exists. It might be a better design for me to just require an `IThreadContext<T>` when calling Start() from `BeginStart`. That would require the caller to provide a context with a synchronization context. This feels like an implementation detail that the engine should handle so I'm not sure. I'll contemplate it a bit more.
